### PR TITLE
Make request object fields public

### PR DESCRIPTION
**Pull request by cryptoquick**
Also, some git noise from format-on-save and some genericization of error data.

...and I didn't realize when I made itthat this PR was upstream :joy_cat: 

Let me know if this is off-track.

### CODE REVIEW

**Comment by kardeiz** [comment]
@cryptoquick I'm not opposed to these changes, but can you provide an example of when you would need to access `id` on the `RequestObject` directly? Also, why just `id` and not `method` and `params` as well? Would it be better to make these available through the `FromRequest` extractor?

**Comment by kardeiz** [comment]
Also making the `Error` `data` generic isn't very useful unless we thread the type parameter through all the handler-related structures, right? That is, with this change, you will be able to construct an `Error<MyDataType>`, but you won't be able to use it in any of the handlers/integrations, since those will all expect the default `Error<BoxedSerialize>`.

**Comment by cryptoquick** [comment]
> @cryptoquick I'm not opposed to these changes, but can you provide an example of when you would need to access `id` on the `RequestObject` directly?

Sure! I'm refactoring some old code that had been forked a while back:

https://github.com/ChainSafe/forest/blob/af2905f278cdffebe23f0baec8713739e40f4928/node/rpc/src/lib.rs#L449

I was originally having trouble with both accessing the data, and send traits on the BoxedError, which I believed what the generic fixed. I don't quite understand the issue well, though, and when I reverted that code, things worked the same as expected. Not sure why.

> Also, why just `id` and not `method` and `params` as well? Would it be better to make these available through the `FromRequest` extractor?

I could try, is that a better approach, you think? This seemed simpler. I only needed the id, but if in case it's potentially useful for others, I added the other fields, too.

> Also making the `Error` `data` generic isn't very useful unless we thread the type parameter through all the handler-related structures, right? That is, with this change, you will be able to construct an `Error<MyDataType>`, but you won't be able to use it in any of the handlers/integrations, since those will all expect the default `Error<BoxedSerialize>`.

I almost went down that road, but I lucked out in that the code compiled without the generic, after all.

**Comment by kardeiz** [comment]
@cryptoquick I merged this, but after working on some other changes for a while, decided to just provide the `id` (and `method`) as extractors in the handler setup. For example, you can now (as of `jsonrpc_v2` `0.8.0`) have a handler method that looks like:

    async fn my_handler(id: Option<jsonrpc_v2::Id) -> Result<String, Error>;

And then use the `id` as needed in the handler.

If this doesn't work for your use case, feel free to let me know here.

**Comment by cryptoquick** [comment]
@kardeiz So, I ran into this again. Do you have a suggestion on a better way to do this?
https://github.com/ChainSafe/forest/blob/e88b30b694cf7a21b83564e130b5f99e4cfd8cf7/node/rpc/src/rpc_ws_handler.rs#L75-L78

**Comment by kardeiz** [comment]
Ah, I see, you are intercepting the JSON-RPC request object. I've added an `id_ref` and `method_ref` on the `RequestObject` in `0.10.0`. Does that resolve your issue?

**Comment by cryptoquick** [comment]
That works great, thank you so much!!

**Pull request merged**
